---
title: "Import Sleep environment ASE"
author: "Johannes Zauner"
format: 
  html:
    self-contained: true
    code-tools: true
editor_options: 
  chunk_output_type: console
---

## Preface

This document imports the `ASE` (Sleep environment) and shows descriptive statistics for the site.

## Setup

```{r}
#| message: false
library(tidyverse)
library(LightLogR)
library(glue)
library(readxl)
library(gt)
library(gtsummary)

remote <- 
  "https://raw.githubusercontent.com/MeLiDosProject/Data_Metadata_Conventions/main/scripts/"

c("labeling",
  "radio_factors",
  "add_label",
  "prepare_codebook",
  "filefinder",
  "general_parameters",
  "coltype_checker",
  "attention_check",
  "tables"
) |> walk(\(x) source(paste0(remote, x, ".R")))
```

## Preparation

```{r}
#collect codebook
codebook <- 
  prepare_codebook("MeLiDosDischargeQuestionnaire_DataDictionary_2024-10-16.csv",
                   "your_sleep_environment_ase")
#collect files
files <- filefinder("discharge",individual = FALSE)
files <- files |> 
          subset(grepl("ASE", files))

#import files
data <- 
  read_csv(files, show_col_types = FALSE) |> 
  rename_with(\(x) str_remove_all(x, "_v2")) |> 
  drop_na(redcap_repeat_instance) |> 
  mutate(
    record_id = str_replace(record_id, "UCR", "UCR_")
  )

  # drop_na(redcap_repeat_instance)
#check column types
coltype_check <- coltype_checker(codebook, data)
coltype_check$details |> gt()
#collect relevant columns
relevant_columns <- 
  coltype_check$details |> 
  pull(col) |> 
  c("record_id")
#select relevant columns
data <- data |> select(any_of(relevant_columns))
#label
data <-
data |> 
  add_radio_factors(codebook, 
                    var_col = `Variable / Field Name`, 
                    type_col = `Field Type`,
                    levels_col = `Choices, Calculations, OR Slider Labels`
                    ) |> 
  add_col_labels(codebook, var_col = `Variable / Field Name`, label_col = `Field Label`)

#reorder variables
data <- 
  data |> 
  relocate(record_id, any_of(codebook$`Variable / Field Name`))
data$record_id <- add_label(data$record_id, "Record ID")
```

## Attention check

```{r}
data <- 
  data |> 
  attention_check(slypos_ase_attentioncheck, "Strongly disagree")
```

## ASE score

```{r}
data <- 
data |> 
  rowwise() |> 
  mutate(
across(starts_with("slypos_ase_0"),
       \(x) {x <- x |> as.numeric()
       x-1
       }, .names = "{.col}_num"),
ASE = sum(c_across(ends_with("_num")), na.rm = TRUE),
.after = record_id
) |> select(-ends_with("_num"))

data <- 
add_labels(data, c(ASE = "ASE score"))
```

## Summarize results

```{r}
table <- 
table_general(data, "ASE: Sleep environment")
table
gtsave(table |> as_gt(), filename = "../output/tables/table_ASE.png", vwidth = 800)
```

### Export

```{r}
data <- data |> rename(Id = record_id)
ase <- data
path <- "../data/imported/"
if(!dir.exists(path)) dir.create(path, recursive = TRUE)
save(ase, file = "../data/imported/ase.RData")
```
