---
title: "Import light"
author: "Johannes Zauner"
format: 
  html:
    self-contained: true
    code-tools: true
---

# Preface

This is a work-in-progress descriptive analysis of the `SanchoSalasEtAl2025` dataset.

```{r}
#| label: setup
#| include: false
library(LightLogR)
library(glue)
library(tidyverse)
library(gt)
library(readxl)
library(cowplot)
library(legendry)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(patchwork)
library(rlang)
library(here)

remote <- 
  "https://raw.githubusercontent.com/MeLiDosProject/Data_Metadata_Conventions/main/scripts/"

c(
  "filefinder",
  "general_parameters",
  "overview_plot"
) |> walk(\(x) source(paste0(remote, x, ".R")))

site <- "UCR"
```

# Overview

## Data import: wearable data

The first step is the import of wearable data from the `head` position (mounted on glasses).

```{r}
#| label: "general information"
#regex to extract participant Id and wearing position
# pattern <- "[A-Z]+_S[0-9]{3}_[hcw]"
#regex to extract participant Id
pattern <- "[A-Z]+_S[0-9]{3}"
```

```{r}
files <- filefinder("actlumus_chest", continuous = TRUE, negate = "Report")
```

```{r}
#there remain some early data from a pilot collection. these will be removed
data <- import$ActLumus(files, tzs[site], auto.id = pattern, dst_adjustment = TRUE)

#change names to conform to group
data <- 
data |> 
  mutate(Id = fct_relabel(Id, \(x) sprintf("UCR_S%03d", parse_number(x))))
```

## Regularizing data

In the first step, we will trim the data by the study time.

```{r}
path_study_dates <- paste0("../data/Study_dates_MeLiDos_", site, ".xlsx")

#import table with study times
Study_dates <- read_excel(path_study_dates)
#gather the important information
Study_dates <-
  Study_dates |> 
    rename(Id = subjectID_device, start = datetime_trial_start, end = datetime_trial_end) |> 
    select(Id, start, end) |> 
    mutate(across(c(start, end), \(x) force_tz(x, tzs[site])),
           trial = TRUE) |> 
    filter(str_detect(Id, "_c$")) |>
    mutate(Id = str_remove(Id, "_c$")) |> 
  group_by(Id)

#add the trim information to the dataset and filter by it
data <- 
  data |> 
  add_states(Study_dates) |> 
  dplyr::filter(trial) |> 
  select(-trial)

data |> gg_overview()
```


```{r}
data |> has_gaps()
data |> has_irregulars()
data |> gg_gaps(group.by.days = TRUE, show.irregulars = TRUE, full.days = FALSE)
```

```{r}
#| fig-height: 15
#| fig-width: 5
data_cleaned <- 
data |> 
  gap_handler(full.days = TRUE)

data_cleaned |> has_gaps() #no more implicit gaps
data_cleaned |> has_irregulars() #no more irregular data
data_cleaned |> gap_table(MEDI) |> cols_hide(ends_with("_n"))
```

## Exporting values

```{r}
light_1min <- 
data_cleaned |> 
  aggregate_Datetime("1 minute", numeric.handler = \(x) mean(x, na.rm = TRUE)) |> 
  remove_partial_data(MEDI, threshold.missing = "3 hours", by.date = TRUE)

light <- data_cleaned

save(light_1min, file = "../data/imported/light/light_1minute.RData")
save(light, file = "../data/imported/light/light.RData")
```

## Visualization

```{r}
#| warning: false
#| message: false
#| fig-height: 8
#| fig-width: 12

prefix <- paste0(site, "_")

data_cleaned |> 
  mutate(Id = Id |> fct_relabel(\(x) str_remove(x, prefix))) |> 
grand_overview(coordinates[[site]], cities[[site]], countries[[site]], 
               country_colors[[site]], photoperiod_sequence = 0.2, ov_y.text.size = 5)

ggsave("../output/figures/Figure_1.png", width = 17, height = 10, scale = 2, units = "cm")
ggsave("../output/figures/Figure_1.jpeg", width = 17, height = 10, scale = 2, units = "cm")
```

## Stats

### Summary table

```{r}
#| message: false
#| warning: false

table_summary <-
summary_table(
  data_cleaned, 
  coordinates = coordinates[[site]], 
  location = cities[[site]], 
  site = countries[[site]], 
  color = country_colors[[site]],
  histograms = TRUE
)

table_summary

gtsave(table_summary, here("output/tables/table_summary.png"), vwidth = 850, expand = 30)
gtsave(table_summary, here("output/tables/table_summary.pdf"))
gtsave(table_summary |> cols_hide(c(plot)), here("output/tables/table_summary.docx"))
```

